apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  ports:
    - nodePort:
      port: 6379
      targetPort: 6379
  selector:
    name: redis-service
    app: demo-voting-app
